desktop_user = [
        "ytd-topbar-menu-button-renderer",
        "ytd-watch-info-text",
        "ytd-thumbnail",
        "tp-yt-paper-button",
        "iron-selector",
        "mask",
        "yt-history-manager",
        "yt-interaction",
        "ytd-rich-section-renderer",
        "ytd-continuation-item-renderer",
        "ytd-permission-role-bottom-bar-renderer",
        "ytd-watch-metadata",
        "yt-image",
        "stop",
        "ytd-rich-grid-renderer",
        "tp-yt-paper-spinner-lite",
        "ytd-masthead",
        "ytd-playlist-thumbnail",
        "ytd-playlist-header-renderer",
        "ytd-comments",
        "ytd-thumbnail-overlay-equalizer",
        "yt-guide-manager",
        "yt-icon",
        "ytd-playlist-panel-renderer",
        "yt-playability-error-supported-renderers",
        "ytd-button-renderer",
        "yt-dynamic-sizing-formatted-string",
        "ytd-miniplayer",
        "yt-hotkey-manager",
        "ytd-watch-flexy",
        "ytd-refresh",
        "rect",
        "ytd-popup-container",
        "ytd-guide-renderer",
        "ytd-logo",
        "polygon",
        "ytd-app",
        "ytd-searchbox",
        "yt-chip-cloud-chip-renderer",
        "ytd-video-meta-block",
        "ytd-guide-signin-promo-renderer",
        "yt-img-shadow",
        "ytd-lottie-player",
        "dom-repeat",
        "yt-button-shape",
        "iron-a11y-announcer",
        "tp-yt-paper-item",
        "circle",
        "ytd-player",
        "ytd-third-party-manager",
        "ytd-rich-shelf-renderer",
        "yt-collections-stack",
        "ytd-rich-grid-slim-media",
        "dom-if",
        "ytd-miniplayer-toast",
        "ytd-watch-next-secondary-results-renderer",
        "ytd-browse",
        "ytd-feed-filter-chip-bar-renderer",
        "tp-yt-app-drawer",
        "icon-shape",
        "ytd-menu-renderer",
        "ytd-ghost-grid-renderer",
        "ytd-banner-promo-renderer",
        "tp-yt-paper-tooltip",
        "lineargradient",
        "ytd-video-quality-promo-renderer",
        "radialgradient",
        "ytd-playlist-sidebar-renderer",
        "ytd-page-manager",
        "ytd-watch-engagement-panels",
        "path",
        "yt-icon-shape",
        "use",
        "ytd-settings-sidebar-renderer",
        "iron-media-query",
        "ytd-badge-supported-renderer",
        "yt-touch-feedback-shape",
        "yt-mdx-manager",
        "ytd-video-primary-info-renderer",
        "ytd-rich-item-renderer",
        "defs",
        "g",
        "yt-playlist-manager",
        "ytd-video-preview",
        "ytd-sentiment-bar-renderer",
        "ytd-mini-guide-entry-renderer",
        "ytd-thumbnail-overlay-now-playing-renderer",
        "ytd-two-column-browse-results-renderer",
        "ytd-channel-name",
        "ytd-thumbnail-overlay-time-status-renderer",
        "tp-yt-paper-spinner",
        "ytd-guide-entry-renderer",
        "ytd-rich-grid-row",
        "yt-icon-button",
        "ytd-topbar-logo-renderer",
        "ytd-mini-guide-renderer",
        "text",
        "clippath",
        "ytd-yoodle-renderer",
        "yt-formatted-string",
        "yt-attributed-string",
        "iron-iconset-svg",
        "ytd-channel-legal-info-renderer",
        "ytd-rich-grid-media",
        "yt-page-navigation-progress",
        "ytd-structured-description-content-renderer",
        "ytd-video-owner-renderer",
        "ytd-text-inline-expander",
        "ytd-metadata-row-container-renderer",
        "ytd-guide-section-renderer"
    ]
desktop_bot = [
        "ytd-topbar-menu-button-renderer",
        "ytd-watch-info-text",
        "ytd-thumbnail",
        "tp-yt-paper-button",
        "iron-selector",
        "mask",
        "yt-history-manager",
        "yt-interaction",
        "ytd-rich-section-renderer",
        "ytd-continuation-item-renderer",
        "ytd-permission-role-bottom-bar-renderer",
        "ytd-watch-metadata",
        "yt-image",
        "stop",
        "ytd-rich-grid-renderer",
        "tp-yt-paper-spinner-lite",
        "ytd-masthead",
        "ytd-playlist-thumbnail",
        "ytd-playlist-header-renderer",
        "ytd-comments",
        "ytd-thumbnail-overlay-equalizer",
        "yt-guide-manager",
        "yt-icon",
        "ytd-playlist-panel-renderer",
        "yt-playability-error-supported-renderers",
        "ytd-button-renderer",
        "yt-dynamic-sizing-formatted-string",
        "ytd-miniplayer",
        "yt-hotkey-manager",
        "ytd-watch-flexy",
        "ytd-refresh",
        "rect",
        "ytd-popup-container",
        "ytd-guide-renderer",
        "ytd-logo",
        "polygon",
        "ytd-app",
        "ytd-searchbox",
        "yt-chip-cloud-chip-renderer",
        "ytd-video-meta-block",
        "ytd-guide-signin-promo-renderer",
        "yt-img-shadow",
        "ytd-lottie-player",
        "dom-repeat",
        "yt-button-shape",
        "iron-a11y-announcer",
        "tp-yt-paper-item",
        "circle",
        "ytd-player",
        "ytd-third-party-manager",
        "ytd-rich-shelf-renderer",
        "yt-collections-stack",
        "ytd-rich-grid-slim-media",
        "dom-if",
        "ytd-miniplayer-toast",
        "ytd-watch-next-secondary-results-renderer",
        "ytd-browse",
        "ytd-feed-filter-chip-bar-renderer",
        "tp-yt-app-drawer",
        "icon-shape",
        "ytd-menu-renderer",
        "ytd-ghost-grid-renderer",
        "ytd-banner-promo-renderer",
        "tp-yt-paper-tooltip",
        "lineargradient",
        "ytd-video-quality-promo-renderer",
        "radialgradient",
        "ytd-playlist-sidebar-renderer",
        "ytd-page-manager",
        "ytd-watch-engagement-panels",
        "path",
        "yt-icon-shape",
        "use",
        "ytd-settings-sidebar-renderer",
        "iron-media-query",
        "ytd-badge-supported-renderer",
        "yt-touch-feedback-shape",
        "yt-mdx-manager",
        "ytd-video-primary-info-renderer",
        "ytd-rich-item-renderer",
        "defs",
        "g",
        "yt-playlist-manager",
        "ytd-video-preview",
        "ytd-sentiment-bar-renderer",
        "ytd-mini-guide-entry-renderer",
        "ytd-thumbnail-overlay-now-playing-renderer",
        "ytd-two-column-browse-results-renderer",
        "ytd-channel-name",
        "ytd-thumbnail-overlay-time-status-renderer",
        "tp-yt-paper-spinner",
        "ytd-guide-entry-renderer",
        "ytd-rich-grid-row",
        "yt-icon-button",
        "ytd-topbar-logo-renderer",
        "ytd-mini-guide-renderer",
        "text",
        "clippath",
        "ytd-yoodle-renderer",
        "yt-formatted-string",
        "yt-attributed-string",
        "iron-iconset-svg",
        "ytd-channel-legal-info-renderer",
        "ytd-rich-grid-media",
        "yt-page-navigation-progress",
        "ytd-structured-description-content-renderer",
        "ytd-video-owner-renderer",
        "ytd-text-inline-expander",
        "ytd-metadata-row-container-renderer",
        "ytd-guide-section-renderer"
    ]

mobile_user = [
        "ytm-app",
        "ytm-bottom-sheet-renderer",
        "ytm-browse",
        "ytm-reel-shelf-renderer",
        "ytm-pivot-bar-renderer",
        "ytm-reel-item-renderer",
        "ytm-media-item",
        "ytm-mobile-topbar-renderer",
        "ytm-rich-section-renderer",
        "path",
        "use",
        "ytm-pivot-bar-item-renderer",
        "ytm-single-column-browse-results-renderer",
        "yt-touch-feedback-shape",
        "ytm-thumbnail-overlay-time-status-renderer",
        "ytm-rich-item-renderer",
        "ytm-badge-and-byline-renderer",
        "c3-icon",
        "g",
        "ytm-channel-thumbnail-with-link-renderer",
        "panel-container",
        "drawer-layout-container",
        "ytm-home-logo",
        "ytm-menu",
        "ytm-rich-grid-renderer",
        "polygon",
        "ytm-chip-divider-renderer",
        "ytm-continuation-item-renderer",
        "bottom-sheet-container",
        "ytm-topbar-menu-button-renderer",
        "ytm-chip-cloud-chip-renderer",
        "ytm-menu-renderer",
        "ytm-tab-renderer",
        "ytm-video-with-context-renderer",
        "ytm-feed-filter-chip-bar-renderer",
        "ytm-profile-icon",
        "ytm-searchbox"
    ]

mobile_bot = [
        "ytm-app",
        "ytm-bottom-sheet-renderer",
        "ytm-browse",
        "ytm-reel-shelf-renderer",
        "ytm-pivot-bar-renderer",
        "ytm-reel-item-renderer",
        "ytm-media-item",
        "ytm-mobile-topbar-renderer",
        "ytm-rich-section-renderer",
        "path",
        "use",
        "ytm-pivot-bar-item-renderer",
        "ytm-single-column-browse-results-renderer",
        "yt-touch-feedback-shape",
        "ytm-thumbnail-overlay-time-status-renderer",
        "ytm-rich-item-renderer",
        "ytm-badge-and-byline-renderer",
        "c3-icon",
        "g",
        "ytm-channel-thumbnail-with-link-renderer",
        "panel-container",
        "drawer-layout-container",
        "ytm-home-logo",
        "ytm-menu",
        "ytm-rich-grid-renderer",
        "polygon",
        "ytm-chip-divider-renderer",
        "ytm-continuation-item-renderer",
        "bottom-sheet-container",
        "ytm-topbar-menu-button-renderer",
        "ytm-chip-cloud-chip-renderer",
        "ytm-menu-renderer",
        "ytm-tab-renderer",
        "ytm-video-with-context-renderer",
        "ytm-feed-filter-chip-bar-renderer",
        "ytm-profile-icon",
        "ytm-searchbox"
    ]

# Find elements present in list1 but not in list2
differences_list1 = [item for item in desktop_user if item not in desktop_bot]

# Find elements present in list2 but not in list1
differences_list2 = [item for item in desktop_bot if item not in desktop_user]

differences_list3 = [item for item in desktop_user if item not in mobile_user]

differences_list4 = [item for item in mobile_user if item not in desktop_user]

differences_list5 = [item for item in mobile_user if item not in mobile_bot]

differences_list6 = [item for item in mobile_bot if item not in mobile_user]

differences_list7 = [item for item in desktop_bot if item not in mobile_bot]

differences_list8 = [item for item in mobile_bot if item not in desktop_bot]

"""
print("Elements in desktop user but not in desktop bot:", differences_list1)
print("Elements in desktop bot but not in desktop user:", differences_list2)
print("--------------------------------------------------------------------")
print("Elements in desktop user but not in mobile user:", differences_list3)
print("Elements in mobile user but not in desktop user:", differences_list4)
print("--------------------------------------------------------------------")

print("Elements in mobile user but not in mobile bot:", differences_list5)
print("Elements in mobile bot but not in mobile user", differences_list6)
print("--------------------------------------------------------------------")
print("Elements in desktop bot but not in mobile bot:", differences_list7)
print("Elements in mobile bot but not in desktop bot:", differences_list8)
"""
difference = [item for item in differences_list8 if item not in differences_list4]
print(difference)